# # Generated by Django 3.0.5 on 2020-04-03 04:28
#
# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('quiz', '0002_auto_20200403_0723'),
#     ]
#
#     operations = [
#         migrations.AlterField(
#             model_name='test',
#             name='time',
#             field=models.PositiveIntegerField(),
#         ),
#     ]
