# Generated by Django 3.0.5 on 2020-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200403_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Article')),
                ('text', models.TextField(verbose_name='Text')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
    ]
